#!/bin/sh

# Apply F-K filter

# Change parameter here
input=Line_001_geom_cdp_d2.su
output=Line_001_geom_cdp_d2_fk.su
ep=32                                # shot no
slopes=-0.5,-0.3,0.3,0.5             # monotonically increasing slopes
amps=0,1,1,0                         # amplitudes corresponding to slopes
bias=0.0                             # slope made horizontal before filtering 
dx=0.025                             # sampling interval in 1st dimension (x-axis or distance)
dt=0.002                             # sampling interval in 2nd dimension (y-axis)

# Take one shot to test
suwind < $input key=ep min=$ep max=$ep > tmp1.su

# Plot and spectrum before F-K filter
output_eps_image_before=${input%.su}_shot-${ep}_before-fk.eps
output_eps_fk_before=${input%.su}_shot-${ep}_spectrum_before-fk.eps
suximage perc=80 title="Shot $ep before F-K filter" label1="Time [s]" label2="Trace" f1=1 d1=1 f2=1 d2=1 < tmp1.su &
supsimage perc=80 < tmp1.su title="Shot $ep before F-K filter" label1="Time [s]" label2="Trace" > $output_eps_image_before &
suspecfk < tmp1.su | suximage perc=97 title="F-K Spectrum of Shot $ep before F-K filter" legend=1 label1="Frequency [Hz]" label2="Wavenumber" cmap=hsv1 &
suspecfk < tmp1.su | supsimage perc=97 title="F-K Spectrum of Shot $ep before F-K filter" legend=1 xbox=2 whls=0.0,0.5,1.0 ghls=0.33,0.5,1.0 bhls=0.66,0.5,1.0 label1="Frequency [Hz]" label2="Wavenumber" > $output_eps_fk_before &

# Filter
sudipfilt < tmp1.su dt=$dt dx=$dx slopes=$slopes amps=$amps bias=$bias > tmp2.su

# After filter
output_eps_image_after=${input%.su}_shot-${ep}_after-fk.eps
output_eps_fk_after=${input%.su}_shot-${ep}_spectrum_after-fk.eps
suximage perc=80 title="Shot $ep after F-K filter" label1="Time [s]" label2="Trace" f1=1 d1=1 f2=1 d2=1 < tmp2.su &
supsimage perc=80 < tmp2.su title="Shot $ep after F-K filter" label1="Time [s]" label2="Trace" > $output_eps_image_after &
suspecfk < tmp2.su | suximage perc=97 title="F-K Spectrum of Shot $ep after F-K filter" legend=1 label1="Frequency [Hz]" label2="Wavenumber" cmap=hsv1 &
suspecfk < tmp2.su | supsimage perc=97 title="F-K Spectrum of Shot $ep after F-K filter" legend=1 xbox=2 whls=0.0,0.5,1.0 ghls=0.33,0.5,1.0 bhls=0.66,0.5,1.0 label1="Frequency [Hz]" label2="Wavenumber" > $output_eps_fk_after &

# Apply to all data
sudipfilt < $input dt=$dt dx=$dx slopes=$slopes amps=$amps bias=$bias > $output

# Clean up temporary file
rm -f tmp1.su tmp2.su
