#!/bin/sh

input=Line_001_geom_cdp_d2_fk_bandpass_decon.su
output=Line_001_geom_cdp_d2_fk_bandpass_decon_fx-decon.su
cdp_min=800
cdp_max=800
vnmo=1700,2750,3000
tnmo=0.1,1.0,2.0
tmin=1
tmax=3
fmin=15
fmax=60
ntrf=159
ntrw=160			# ntrw > ntrf
taper=0.01

# Take one CDP to test
suwind < $input key=cdp min=$cdp_min max=$cdp_max > tmp1.su

sunmo < tmp1.su tnmo=$tnmo vnmo=$vnmo | suwind tmin=$tmin tmax=$tmax > tmp2.su

sunmo < tmp1.su tnmo=$tnmo vnmo=$vnmo | sufxdecon fmin=$fmin fmax=$fmax ntrf=$ntrf ntrw=$ntrw taper=$taper | suwind tmin=$tmin tmax=$tmax > tmp3.su

suximage < tmp2.su perc=95 title="before fx decon" &
suximage < tmp3.su perc=95 title="after fx decon" &
suop2 tmp2.su tmp3.su op=diff | suximage perc=95 title="diff" &
