#!/bin/sh

# Apply normal move out

#Parameter
input=Line_001_geom_cdp_d2_fk_bandpass_decon.su
output=Line_001_geom_cdp_d2_fk_bandpass_decon_nmo.su
vnmo=1700,2750,3000
tnmo=0.1,1.0,2.0
cdp_min=1000
cdp_max=1002

# Do NMO
sunmo vnmo=$vnmo tnmo=$tnmo < $input > $output

# Plot NMO on cdp
suwind < $output key=cdp min=$cdp_min max=$cdp_max | suxwigb perc=95 title="NMO CDP $cdp_min - $cdp_max" label1="Time [s]" label2="CDP" &
